import type { OrblyTheme } from "@orbly/features";
import { StyleSheet } from "react-native";

import { POST_ACTION_MAX_WIDTH } from "@/constants/layout";

const ACTION_ICON_WRAP = 28;

export function createPostCardStyles(c: OrblyTheme) {
  return StyleSheet.create({
    card: {
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    cardHighlight: { backgroundColor: "rgba(29, 155, 240, 0.06)" },
    row: { flexDirection: "row", gap: 12 },
    avatarCol: { width: 40 },
    body: { flex: 1, minWidth: 0 },
    repostRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginBottom: 4,
    },
    repostLabel: { color: c.textSecondary, fontSize: 13, fontWeight: "600" },
    headRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 8,
    },
    headNames: { flex: 1, minWidth: 0 },
    nameMetaRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      alignItems: "center",
      columnGap: 4,
      rowGap: 2,
    },
    displayName: {
      color: c.textPrimary,
      fontWeight: "700",
      fontSize: 15,
      flexShrink: 1,
      maxWidth: "55%",
    },
    handle: { color: c.textSecondary, fontSize: 15, flexShrink: 1 },
    metaDot: { color: c.textSecondary, fontSize: 15 },
    metaTime: { color: c.textSecondary, fontSize: 15 },
    menuBtn: { padding: 6, marginTop: -2, marginRight: -6 },
    liveBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      alignSelf: "flex-start",
      backgroundColor: "rgba(249,24,128,0.12)",
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      marginBottom: 8,
    },
    liveBadgeText: { color: c.like, fontWeight: "700", fontSize: 13 },
    orbitPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      alignSelf: "flex-start",
      marginTop: 4,
      marginBottom: 2,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: "rgba(120, 86, 255, 0.12)",
    },
    orbitPillText: { color: c.orbit, fontSize: 13, fontWeight: "600" },
    replyingToLine: { fontSize: 13, color: c.textSecondary, marginTop: 2 },
    replyingToUser: { color: c.accent, fontWeight: "600" },
    contentWrap: { marginTop: 2 },
    embedWrap: { marginTop: 12 },
    blockSpacing: { marginTop: 12 },
    mediaWrap: {
      marginTop: 12,
      borderRadius: 16,
      overflow: "hidden",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    mediaWrapSingle: { maxWidth: 508 },
    mediaWrapMulti: {},
    mediaGrid: {},
    mediaGridMulti: { flexDirection: "row", flexWrap: "wrap", gap: 2 },
    media: { width: "100%", backgroundColor: c.bgSecondary },
    mediaSingle: { height: 280, maxHeight: 400 },
    mediaHalf: { width: "49.5%", height: 140 },
    mediaTripleLead: { width: "49.5%", height: 288 },
    actions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      alignSelf: "flex-start",
      width: "100%",
      maxWidth: POST_ACTION_MAX_WIDTH,
      marginTop: 12,
      marginLeft: -8,
    },
    repostGroup: { flexDirection: "row", alignItems: "center" },
    actionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
      padding: 8,
      minWidth: 36,
    },
    actionIconWrap: {
      width: ACTION_ICON_WRAP,
      height: ACTION_ICON_WRAP,
      borderRadius: ACTION_ICON_WRAP / 2,
      alignItems: "center",
      justifyContent: "center",
    },
    actionIconWrapRepost: { backgroundColor: "rgba(0, 186, 124, 0.15)" },
    actionIconWrapLike: { backgroundColor: "rgba(249, 24, 128, 0.12)" },
    actionIconWrapBookmark: { backgroundColor: "rgba(29, 155, 240, 0.1)" },
    actionCount: {
      color: c.textSecondary,
      fontSize: 13,
      fontVariant: ["tabular-nums"],
    },
    repostCountBtn: { paddingVertical: 8, paddingRight: 4, marginLeft: -6 },
  });
}

export type PostCardStyles = ReturnType<typeof createPostCardStyles>;
